### ISSUE TITLE
zoom ancestor frames

### ISSUE THREAD

**Issue by brendangregg** [cimi/flame-graph-d3#22]
When zooming, the ancestor frames disappear. I think it's better to leave them on the screen for context, although faded in color to show that they aren't showing the entire width.

The example prints the ancestor context on the top right as text. I'd argue that showing the ancestor frames was more intuitive and better related to the existing visualization. So when zooming, the user needs to learn something a little different (faded = partial), rather than something more different (missing = zoomed & ancestors are on top right as text).

**Comment by cimi** [comment]
This is a great idea. It will involve a bit of re-work, but I'm keen on doing it.

**Comment by cimi** [comment]
I've almost wrapped this up, but I need to do some refactoring as it became slightly messy. I also need to add on click behaviour to the ancestor nodes - so the previous state of the graph is restored.

I'll try and finish it this evening.

**Comment by cimi** [comment]
I've updated [the demo page](http://cimi.github.io/d3-flame-graphs/) to reflect this change, thanks for the idea!
